# -*- coding: utf-8 -*-
"""lab3 outliers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xl5ECA5kezoE2jbYUbjGZnVpTYm3r4zk
"""

import pandas as pd
import seaborn as sn

df = pd.read_excel("weight-height.xlsx")
df



df = pd.read_excel("weight-height.xlsx")
df

sn.histplot(df.Height, kde=True)

mean = df.Height.mean()
mean

std_deviation = df.Height.std()
std_deviation

lower= mean-3*std_deviation
lower

upper = mean+3*std_deviation

df[(df.Height < lower) | (df.Height > 77.91)]

df_no_outlier = df[(df.Height<77.91) & (df.Height>54.82)]
df_no_outlier.shape

# calculate z score

df['zscore'] = ( df.Height - df.Height.mean() ) / df.Height.std()
df.head(5)

Jn df.Height.mean()

df.Height.std()

(73.84-66.37)/3.84

df[df['zscore']>3]

df[df['zscore']<-3]

# You are given bhp.csv which contains property prices in the city of banglore, India. You need to examine price_per_sqft column and do following,

# (1) Remove outliers using percentile technique first. Use [0.001, 0.999] for lower and upper bound percentiles

# (2) After removing outliers in step 1, you get a new dataframe.

# (3) On step(2) dataframe, use 4 standard deviation to remove outliers

# (4) Plot histogram for new dataframe that is generated after step (3). Also plot bell curve on same histogram

# (5) On step(2) dataframe, use zscore of 4 to remove outliers. This is quite similar to step (3) and you will get exact same result

