# -*- coding: utf-8 -*-
"""lab4_logNormal

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1joEWUUsNMEElOB5KFqXY9cqa9TAHPrP4
"""

import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
import numpy as np
import seaborn as sn



# Generate a right-skewed distribution
data = np.random.gamma(2, size=1000)

# Plot the histogram of the data
plt.hist(data, bins=30)
plt.title('Right-skewed distribution')
plt.show()

# Apply the Box-Cox transformation
data_bc, lambda_ = stats.boxcox(data)

# Plot the histogram of the transformed data
plt.hist(data_bc, bins=30)
plt.title('Box-Cox transformed data')
plt.show()

# Check if the transformed data is approximately normal
print(stats.normaltest(data_bc))

# Generate right-skewed data
data = np.random.exponential(scale=2, size=1000)
plt.hist(data, bins=30)
plt.show()

# Perform log transformation
transformed_data = np.log(data)

# Plot histogram of the transformed data
plt.hist(transformed_data, bins=30)
plt.show()

df = pd.read_csv("coffee.csv")

plt.hist(df["Open"], bins=30)
plt.show()

data = df["Open"]
plt.hist(data, bins=30)
plt.show()
sn.histplot(data, kde=True)

# Perform log transformation
transformed_data = np.log(data)

# Plot histogram of the transformed data
plt.hist(transformed_data, bins=30)
plt.show()
sn.histplot(transformed_data, kde=True)

df1 = pd.read_csv("income.csv")
data = df1["fnlwgt"]
plt.hist(data, bins=30)
plt.show()
sn.histplot(data, kde=True)

# Perform log transformation
transformed_data = np.log(data)

# Plot histogram of the transformed data
plt.hist(transformed_data, bins=30)
plt.show()
sn.histplot(transformed_data, kde=True)

# Generate some right-skewed data
data = np.random.exponential(scale=2, size=1000)

# Perform the Box-Cox transformation
data_bc, lam = stats.boxcox(data)

# Plot the original and transformed data
fig, (ax1, ax2) = plt.subplots(1, 2)
ax1.hist(data, bins=50)
ax1.set_title('Original Data')
ax2.hist(data_bc, bins=50)
ax2.set_title('Transformed Data (Box-Cox)')
plt.show()